### ISSUE TITLE
Custom markup and class for console log empty state

### ISSUE THREAD

**Issue by dexterca** [MyPureCloud/developer-tools#10]
Can we add a custom class and markup to console log empty state message? I want to match content and styling of other empty states.

<img width="1165" alt="no-log-empty" src="https://cloud.githubusercontent.com/assets/485903/17901197/5fe2d05c-6930-11e6-99c8-83ff8467f18d.png">

**Comment by KevinGlinski** [comment]
@dexterca, added in the mispelled consoleempytstate branch if you want to style it

**Comment by dexterca** [comment]
Completed with https://github.com/MyPureCloud/developer-tools/commit/51b52087914adea3cd61b2b7b8dea9a9657674d0
