### ISSUE TITLE
Add class to parent element of ace editor

### ISSUE THREAD

**Issue by dexterca** [MyPureCloud/developer-tools#12]
Add `.log-editor` class to parent `<li>` of `.editor.ace_editor`

This will enable me to explore using flexbox for better resizing of ace editor panes in console output.

<img width="500" alt="screen shot 2016-08-24 at 1 18 42 pm" src="https://cloud.githubusercontent.com/assets/485903/17940641/0856236a-69fe-11e6-8046-dc78cb4191d8.png">

**Comment by KevinGlinski** [comment]
aea309e
