### ISSUE TITLE
Add selected code sample name to dropdown

### ISSUE THREAD

**Issue by dexterca** [MyPureCloud/developer-tools#9]
Add selected code sample name to dropdown so it matches selected SKD version number:

<img width="400" alt="screen shot 2016-08-23 at 12 43 52 pm" src="https://cloud.githubusercontent.com/assets/485903/17901043/ab10eb32-692f-11e6-9ae5-62e1e9540a40.png">

**Comment by KevinGlinski** [comment]
the code samples can (and should be edited).  If you load the status sample and edit the heck out of it, or leave the app and come back to it later, should it still say the sample that was loaded that might not be relevant any more?

**Comment by KevinGlinski** [comment]
perhaps we can change the drop down to say "load code sample"

**Comment by dexterca** [comment]
Kevin brought up some good points, so I'm closing this.
